In [5]:
import numpy as np

In [6]:
# data
X1 = (39,52,48,46,61,34,25,55)
X2 = (8,6,7,12,9,6,10,4)
y  = (7,6,7,10,9,4,3,4)
I = (1,1,1,1,1,1,1,1)

X = np.array((I,X1,X2)).transpose()
print(X)

[[ 1 39  8]
 [ 1 52  6]
 [ 1 48  7]
 [ 1 46 12]
 [ 1 61  9]
 [ 1 34  6]
 [ 1 25 10]
 [ 1 55  4]]


In [7]:
# Calc X^TX
XTX = X.transpose().dot(X)
print("X^TX :")
print("")
print(XTX)
print("")

# Calc (X^TX)^(-1)
XTXN1 = np.linalg.inv(XTX)
print("(X^TX)^(-1) :")
print("")
print(XTXN1)
print("")

# Calc (X^TX)^(-1)X^T
XTXN1XT = XTXN1.dot(X.transpose())
print("(X^TX)^(-1)X^T:")
print("")
print(XTXN1XT)
print("")


X^TX :

[[    8   360    62]
 [  360 17172  2735]
 [   62  2735   526]]

(X^TX)^(-1) :

[[ 4.70937295e+00 -6.00410184e-02 -2.42906726e-01]
 [-6.00410184e-02  1.10434213e-03  1.33491906e-03]
 [-2.42906726e-01  1.33491906e-03  2.35916604e-02]]

(X^TX)^(-1)X^T:

[[ 0.42451943  0.12979964  0.12705699 -0.9673946  -1.1392897   1.21053797
   0.77928024  0.43549004]
 [-0.00629232  0.00539429  0.00231184  0.00677775  0.01933812 -0.01448387
  -0.01908327  0.00603747]
 [-0.0021116  -0.03194097 -0.01368899  0.10159948  0.05084828 -0.05596952
   0.02638285 -0.07511954]]



In [31]:
#Calc beta_head =(X^TX)^(-1)X^Ty
beta_hat = XTXN1XT.dot(y) 
print("beta_hat = (X^TX)^(-1)X^Ty :"  )
print("")
print(beta_hat)
print("")
print("const :", beta_hat[0], " X1 :", beta_hat[1], " X2 :", beta_hat[2])
print("")
Ypred = X.dot(beta_hat)
print("estimated value 𝐘ˆ=𝐗⋅𝜷̂ :")
print("")
print(Ypred)

beta_hat = (X^TX)^(-1)X^Ty :

[-6.36576782  0.15528749  0.72617169]

const : -6.365767821169365  X1 : 0.1552874930220134  X2 : 0.7261716948617738

estimated value 𝐘ˆ=𝐗⋅𝜷̂ :

[5.49981797 6.06621199 6.17123371 9.4915172  9.64231451 3.27103711
 4.77813645 5.07973107]


In [32]:
#Calc Residuals u_head = (I-H)

# H = hat Matrix
H = X.dot(XTXN1XT)
print("H = hat matrix :")
print(H)
print("")

#I Identity Matrix
I = np.identity(len(H))
print("I = identity matrix :")
print(I)
print("")

u_hat = np.subtract(I, H).dot(y)
print("Residuals u_hat = (I-H)y :")
print(u_hat)
print("")

RSS = np.sum(np.square(u_hat))
print("RSS = Residual sum of squares, RSS = sum(u_hat^2)")
print(RSS)
print("")

sigma_hat_2 = RSS / (len(X)-2-1)
print("sigma_hat_2 = RSS / (n-k-1), n = #samples, k = #predictors,")
print(sigma_hat_2)

H = hat matrix :
[[ 0.16222604  0.08464904  0.10770673  0.10973338  0.02168333  0.19791085
   0.24609536  0.06999527]
 [ 0.08464904  0.21865671  0.16513859 -0.00535485  0.17138237  0.12155955
  -0.05475292  0.29872151]
 [ 0.10770673  0.16513859  0.14220225  0.06913364  0.14487816  0.12352552
   0.04796303  0.19945208]
 [ 0.10973338 -0.00535485  0.06913364  0.56357552  0.36044331 -0.12735431
   0.21804386 -0.18822055]
 [ 0.02168333  0.17138237  0.14487816  0.36044331  0.49797032 -0.17670384
  -0.14735383  0.12770018]
 [ 0.19791085  0.12155955  0.12352552 -0.12735431 -0.17670384  0.38226924
   0.28874603  0.19004696]
 [ 0.24609536 -0.05475292  0.04796303  0.21804386 -0.14735383  0.28874603
   0.56602692 -0.16476845]
 [ 0.06999527  0.29872151  0.19945208 -0.18822055  0.12770018  0.19004696
  -0.16476845  0.46707301]]

I = identity matrix :
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.

In [33]:
#Calc Std.Error Coefficents beta_hat[i] / std_error[i]
print("Std. Error Coefficents")
print("")
print("const :", np.sqrt(XTXN1[0,0]*sigma_hat_2)) 
print("")
print("X1:", np.sqrt(XTXN1[1,1]*sigma_hat_2)) 
print("")
print("X2:", np.sqrt(XTXN1[2,2]*sigma_hat_2)) 



Std. Error Coefficents

const : 2.8247920549673764

X1: 0.04325703623045495

X2: 0.19993286732127746


In [34]:
#Calc t-values for Coefficents
print("t-Values Coefficents")
print("")
print("const :", beta_hat[0]/np.sqrt(XTXN1[0,0]*sigma_hat_2)) 
print("")
print("X1:", beta_hat[1]/np.sqrt(XTXN1[1,1]*sigma_hat_2)) 
print("")
print("X2:", beta_hat[2]/np.sqrt(XTXN1[2,2]*sigma_hat_2)) 

t-Values Coefficents

const : -2.253535020383256

X1: 3.5898782384143972

X2: 3.6320776298119566


In [35]:
print("p-Values Coefficients")
print("")
print("const :", (beta_hat[0]/np.sqrt(XTXN1[0,0]*sigma_hat_2))/8)

p-Values Coefficients

const : -0.281691877547907


In [36]:
# Calc 
#1. const: σ^2 = Σ (x i - μ) 2 / N.


In [47]:
#const
# sqrt(diag(X.T X)^(-1)X.T diag(e_i^(2)) X(X.T X)^(-1)
const_omega = np.full(len(X),sigma_hat_2)
print("const_omega")
print(const_omega)
print("")
const_ = XTXN1XT.dot(np.diag(const_omega)).dot(X).dot(XTXN1)
print("Const - Matrix:   = (X.T X)^(-1)X.T diag(const_omega) X(X.T X)^(-1)")
print(const_)
print("")
const_se = np.sqrt(np.diag(const_))
print("StdError: const_se = sqrt(diag(const_se))")
print(HC0_se)

const_omega
[1.69437635 1.69437635 1.69437635 1.69437635 1.69437635 1.69437635
 1.69437635 1.69437635]

Const - Matrix:   = (X.T X)^(-1)X.T diag(const_omega) X(X.T X)^(-1)
[[ 7.97945015e+00 -1.01732082e-01 -4.11575411e-01]
 [-1.01732082e-01  1.87117118e-03  2.26185528e-03]
 [-4.11575411e-01  2.26185528e-03  3.99731514e-02]]

StdError: const_se = sqrt(diag(const_se))
[2.02832183 0.03955331 0.11967825]


In [38]:
#HCO
# sqrt(diag(X.T X)^(-1)X.T diag(e_i^(2)) X(X.T X)^(-1)
u_hat_2 = u_hat**2
HC0_omega = u_hat_2
print("HC0_omega")
print(HC0_omega)
print("")
HC0 = XTXN1XT.dot(np.diag(u_hat_2)).dot(X).dot(XTXN1)
print("HC0 - Matrix:  HCO = (X.T X)^(-1)X.T diag(u_hat_2) X(X.T X)^(-1)")
print(HC0)
print("")
HC0_se = np.sqrt(np.diag(HC0))
print("StdError: HC0_se = sqrt(diag(HC0))")
print(HC0_se)
print("")
print("beta_hat_HC0 = HC0y :"  )
print("")
print(y)

HC0_omega
[2.25054614 0.00438403 0.68685357 0.25855476 0.41256793 0.53138689
 3.16176925 1.16581919]

HC0 - Matrix:  HCO = (X.T X)^(-1)X.T diag(e_i^(2)) X(X.T X)^(-1)
[[ 4.11408945e+00 -6.98628036e-02 -6.16799203e-02]
 [-6.98628036e-02  1.56446466e-03 -1.09868721e-03]
 [-6.16799203e-02 -1.09868721e-03  1.43228835e-02]]

StdError: HC0_se = sqrt(diag(HC0))
[2.02832183 0.03955331 0.11967825]

beta_hat_HC0 = HC0y :

(7, 6, 7, 10, 9, 4, 3, 4)


In [39]:
#HC1 
#sqrt(diag(n/(n-k)*HC0)
v = len(X)/((len(X)-len(beta_hat)))
HC1_omega = v*u_hat_2
print("HC1 Omega")
print(HC1_omega)
print("")
HC1 = v*HC0
HC1
print("HC1 - Matrix:  HC1 = n/(n-k)*HC0, n = #samples, k = #predictors")
print(HC1)
print("")
HC1_se = np.sqrt(np.diag(HC1))

print("StdError: HC1_se = np.sqrt(np.diag(HC1))")
print(HC1_se)

HC1 Omega
[3.60087382 0.00701444 1.09896571 0.41368762 0.66010868 0.85021903
 5.05883079 1.86531071]

HC1 - Matrix:  HC1 = n/(n-k)*HC0, n = #samples, k = #predictors
[[ 6.58254312e+00 -1.11780486e-01 -9.86878725e-02]
 [-1.11780486e-01  2.50314345e-03 -1.75789953e-03]
 [-9.86878725e-02 -1.75789953e-03  2.29166136e-02]]

StdError: HC1_se = np.sqrt(np.diag(HC1))
[2.56564672 0.05003142 0.15138234]


In [40]:
#HC2
#(X.T X)^(-1)X.T diag(e_i^(2)/(1-h_ii)) X(X.T X)^(-1) where h_ii = x_i(X.T X)^(-1)x_i.T
# HC2_omega = u_hat^(2)/(1-h_ii)
h_ii = np.diag(H)
v1 = (1,1,1,1,1,1,1,1)
uu = np.subtract(v1,h_ii)
HC2_omega =np.divide(u_hat_2,uu)
print("HC2_omega")
print(HC2_omega)
print("")
HC2 = XTXN1XT.dot(np.diag(np.divide(u_hat_2,uu))).dot(X).dot(XTXN1)
print("HC2")
print(HC2)
print("")
print("StdError: HC2_se")
HC2_se = np.sqrt(np.diag(HC2))
print(HC2_se)

HC2_omega
[2.68634052e+00 5.61088451e-03 8.00717382e-01 5.92438723e-01
 8.21799864e-01 8.60224113e-01 7.28563445e+00 2.18757768e+00]

HC2
[[ 8.21811529e+00 -1.46603907e-01 -8.97174863e-02]
 [-1.46603907e-01  3.35876116e-03 -2.73746645e-03]
 [-8.97174863e-02 -2.73746645e-03  2.85182802e-02]]

StdError: HC2_se
[2.86672553 0.05795482 0.16887356]


In [41]:
#HC3
#(X.T X)^(-1)X.T diag(e_i^(2)/(1-h_ii)^(2)) X(X.T X)^(-1), resid^(2)/(1-h_ii)^(2)
# HC2 = u_hat^(2)/(1-h_ii)
h_ii = np.diag(H)
v1 = (1,1,1,1,1,1,1,1)
uu = np.subtract(v1,h_ii)**2
HC3_omega =np.divide(u_hat_2,uu)
print("HC3_omega")
print(HC3_omega)
print("")
HC3 = XTXN1XT.dot(np.diag(np.divide(u_hat_2,uu))).dot(X).dot(XTXN1)
print("HC3")
print(HC3)
print("")
HC3_se = np.sqrt(np.diag(HC3))
print("StdError: HC3_se")
print(HC3_se)

HC3_omega
[3.20652185e+00 7.18107465e-03 9.33457082e-01 1.35748280e+00
 1.63695473e+00 1.39255509e+00 1.67882174e+01 4.10483558e+00]

HC3
[[ 1.70024503e+01 -3.16536334e-01 -1.16255852e-01]
 [-3.16536334e-01  7.36222282e-03 -6.62893362e-03]
 [-1.16255852e-01 -6.62893362e-03  5.76527028e-02]]

StdError: HC3_se
[4.12340276 0.0858034  0.24010977]


In [44]:
#HC4
h_ii = np.diag(H)
v1 = (1,1,1,1,1,1,1,1)
phi = min(4,np.mean(h_ii))
uu = np.subtract(v1,h_ii)**phi
HC4_omega =np.divide(u_hat_2,uu)
print("HC4_omega")
print(HC4_omega)
print("")
HC4 = XTXN1XT.dot(np.diag(HC4_omega)).dot(X).dot(XTXN1)
print("HC4")
print(HC4)
print("")
HC4_se = np.sqrt(np.diag(HC4))
print("StdError: HC4_se")
print(HC4_se)


HC4_omega
[2.40500148 0.00480903 0.7275198  0.35284716 0.53422221 0.63659193
 4.32395956 1.47615107]

HC4
[[ 5.30753211e+00 -9.18734822e-02 -7.15920170e-02]
 [-9.18734822e-02  2.07725412e-03 -1.55402997e-03]
 [-7.15920170e-02 -1.55402997e-03  1.85091960e-02]]

StdError: HC4_se
[2.30380818 0.0455769  0.13604851]


In [ ]:
#HAC Plotten